---
title: "Collate Raw HFA Data"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "compile_mult_reg_results.R"))
source(path(here(), "R", "compile_results.R"))
# source('~/Projects/nice_r_functions/ggpaired_pretty.R')
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "load_and_collate_reg_results.R"))


## plotting helpers ##
ggthemr("solarized")
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

## parallelization ##
nCores <- 4
registerDoParallel(nCores)



#find . -type f -mtime +10 -maxdepth 1 -exec mv {} before_3-21-21 \;
```


## Collate the raw HFA data

Useful for various plotting and such, creates files:

* "/munge/all_brain_data_pres_1_3_2022.csv")
* "/munge/all_brain_data_pre_choice_1_3_2022.csv")
* "/munge/all_brain_data_post_choice_1_3_2022.csv")


```{r load-power-behave-data, echo = F}

subs <- c("IR9", "IR16", "IR19", "IR26", "IR28", "IR35", "IR57", "IR39", "GP51", "DA9", "ST40")

all_brain_data_pres <- NULL
all_brain_data_pre_choice <- NULL
all_brain_data_post_choice <- NULL
for(sub in subs){

  ## read in data ##
  path_hp_clean <- path(here(), "munge", sub, "hfa_behave_presentation_rscaler_2575_200.csv")
  power_behave <-  read.csv(path_hp_clean)
  # merge with elecs #
  brain_behave_data <- power_behave %>%
    select(!( starts_with(paste0("bin_", c(16:37)))) ) %>%
    mutate(subject = sub) %>%
    rowwise() %>%
    mutate(pie_size = self_var_payoff + other_var_payoff) %>%
    mutate(ratio = other_var_payoff / self_var_payoff) %>%
    mutate(max_self = max(self_var_payoff, 10)) %>%
    mutate(max_other = max(other_var_payoff, 10)) %>%
    mutate(min_self = min(self_var_payoff, 10)) %>%
    mutate(min_other = min(other_var_payoff, 10)) %>%
    mutate(max = max(self_var_payoff, other_var_payoff)) %>%
    mutate(min = min(self_var_payoff, other_var_payoff)) %>%
    mutate(trial_type = if_else(self_var_payoff == other_var_payoff, "equality",
                                if_else(self_var_payoff > other_var_payoff,
                                        "Advantageous", "Disadvantageous"))) %>%
    mutate(electrodes = gsub("POL ", "", electrodes)) %>%
    mutate(electrodes = gsub(" POL", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref-", "-", electrodes))
  
  if(is.null(all_brain_data_pres)){
    all_brain_data_pres <- brain_behave_data
  } else {
    all_brain_data_pres <- rbind(all_brain_data_pres, brain_behave_data)
  }
  
  ## read in data ##
  path_hp_clean <- path(here(), "munge", sub, "hfa_behave_choice_rscaler_2575_200.csv")
  power_behave <-  read.csv(path_hp_clean)
  # merge with elecs #
  brain_behave_data <- power_behave %>%
    select(!starts_with("post_")) %>%
    mutate(subject = sub) %>%
    rowwise() %>%
    mutate(pie_size = self_var_payoff + other_var_payoff) %>%
    mutate(ratio = other_var_payoff / self_var_payoff) %>%
    mutate(max_self = max(self_var_payoff, 10)) %>%
    mutate(max_other = max(other_var_payoff, 10)) %>%
    mutate(min_self = min(self_var_payoff, 10)) %>%
    mutate(min_other = min(other_var_payoff, 10)) %>%
    mutate(max = max(self_var_payoff, other_var_payoff)) %>%
    mutate(min = min(self_var_payoff, other_var_payoff)) %>%
    mutate(trial_type = if_else(self_var_payoff == other_var_payoff, "equality",
                                if_else(self_var_payoff > other_var_payoff,
                                        "Advantageous", "Disadvantageous"))) %>%
    mutate(electrodes = gsub("POL ", "", electrodes)) %>%
    mutate(electrodes = gsub(" POL", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref-", "-", electrodes))
  
  if(is.null(all_brain_data_pre_choice)){
    all_brain_data_pre_choice <- brain_behave_data
  } else {
    all_brain_data_pre_choice <- rbind(all_brain_data_pre_choice, brain_behave_data)
  }
  

  # merge with elecs #
  brain_behave_data <- power_behave %>%
    select(!starts_with("pre_")) %>%
    mutate(subject = sub) %>%
    rowwise() %>%
    mutate(pie_size = self_var_payoff + other_var_payoff) %>%
    mutate(ratio = other_var_payoff / self_var_payoff) %>%
    mutate(max_self = max(self_var_payoff, 10)) %>%
    mutate(max_other = max(other_var_payoff, 10)) %>%
    mutate(min_self = min(self_var_payoff, 10)) %>%
    mutate(min_other = min(other_var_payoff, 10)) %>%
    mutate(max = max(self_var_payoff, other_var_payoff)) %>%
    mutate(min = min(self_var_payoff, other_var_payoff)) %>%
    mutate(trial_type = if_else(self_var_payoff == other_var_payoff, "equality",
                                if_else(self_var_payoff > other_var_payoff,
                                        "Advantageous", "Disadvantageous"))) %>%
    mutate(electrodes = gsub("POL ", "", electrodes)) %>%
    mutate(electrodes = gsub(" POL", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref", "", electrodes)) %>%
    mutate(electrodes = gsub("-Ref-", "-", electrodes))
  
  if(is.null(all_brain_data_post_choice)){
    all_brain_data_post_choice <- brain_behave_data
  } else {
    all_brain_data_post_choice <- rbind(all_brain_data_post_choice, brain_behave_data)
  }


}

write_csv(all_brain_data_pres, path(here(), "/munge/all_brain_data_pres_1_3_2022.csv"))
write_csv(all_brain_data_pre_choice, path(here(), "/munge/all_brain_data_pre_choice_1_3_2022.csv"))
write_csv(all_brain_data_post_choice, path(here(), "/munge/all_brain_data_post_choice_1_3_2022.csv"))

```