---
title: "Split Localization"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
# library(summarytools)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(ggalluvial)
library(factoextra)
library(NbClust)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "compile_mult_reg_results.R"))
source(path(here(), "R", "compile_mult_reg_results.R"))
# source('~/Projects/nice_r_functions/ggpaired_pretty.R')
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "load_and_collate_reg_results.R"))



## plotting helpers ##
ggthemr("light")
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 4
# registerDoParallel(nCores)
# 


#find . -type f -mtime +10 -maxdepth 1 -exec mv {} before_3-21-21 \;
```


## Brain Figure Prep

Plotting helpers to plot the inequity dependent effects on the brain


```{r load-data}
# load permuted regressor results #
split_ofc_encoding_reg_df <- read_csv(path(here(), "results", "single_regressions",
                                       "compiled_ofc_ogpermutation_wpvalues_single_regressions_1_28_2022.csv"))

# load permuted trial results #
split_ofc_encoding_ttype_df <- read_csv(path(here(), "results", "single_regressions",
                                       "compiled_ofc_ogpermutation_ttype_wpvalues_single_regressions_1_28_2022.csv"))

# rename test stats and combine #
split_ofc_encoding_reg_df <- split_ofc_encoding_reg_df %>%
  rename(test_stat_real_reg = test_stat_real) %>%
  rename(permuted_p_reg = permuted_p)

split_ofc_encoding_ttype_df <- split_ofc_encoding_ttype_df %>%
  rename(test_stat_real_ttype = test_stat_real) %>%
  rename(permuted_p_ttype = permuted_p)

split_ofc_encoding_df <- full_join(split_ofc_encoding_reg_df, split_ofc_encoding_ttype_df)


```

```{r alternate-hyp-removal}

## electrodes with differences in noise between trial types ##
trial_dep_noise_df <- read_csv(path(here(), "results", "trial_dep_differences_noise.csv"))


## electrodes better explained by max/min unified encoding ##
split_v_uni_max_df <- read_csv(path(here(), "results", "unified_max_split_elecs.csv"))

```

```{r prep-dfs}

## exclude elecs from alt explanantion analyses ##
split_ofc_encoding_df <- split_ofc_encoding_df %>%
  mutate(elec_epoch_ids = paste(subject, electrode, epoch, sep = "_")) %>%
  mutate_cond(elec_epoch_ids %in% trial_dep_noise_df$elec_epoch_ids, permuted_p_reg =1, permuted_p_ttype = 1) %>%
  mutate_cond(reg_id %in% split_v_uni_max_df$reg_id, permuted_p_reg =1, permuted_p_ttype = 1)


# percentage of elecs acros epochs
split_ofc_encoding_reg_sig <- split_ofc_encoding_df %>%
  filter(permuted_p_reg < 0.05) %>%
  select(subject, electrode, predictor, epoch, permuted_p_reg) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100)

split_ofc_encoding_ttype_sig <- split_ofc_encoding_df %>%
  filter(permuted_p_ttype < 0.05) %>%
  select(subject, electrode, predictor, epoch, permuted_p_ttype) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100)


split_ofc_encoding_sig <- split_ofc_encoding_df %>%
  filter(permuted_p_ttype < 0.05 & permuted_p_reg < 0.05) %>%
  select(subject, electrode, predictor, epoch, permuted_p_ttype, permuted_p_reg) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100)


# fdr correctyed df 
split_ofc_encoding_df_fdr <- split_ofc_encoding_df %>%
  select(reg_id, subject, electrode, predictor, epoch, permuted_p_reg, permuted_p_ttype) %>%
  distinct() %>%
  group_by(epoch, predictor) %>%
  mutate(perm_p_reg_fdr = p.adjust(permuted_p_reg, method = "fdr")) %>%
  mutate(perm_p_ttype_fdr = p.adjust(permuted_p_ttype, method = "fdr"))


scatter_plot_r2_df <- split_ofc_encoding_df %>%
  group_by(reg_id) %>%
  mutate(mean_adv = mean(Advantageous)) %>%
  mutate(mean_dis = mean(Disadvantageous)) %>%
  select(mean_adv, mean_dis, reg_id) %>%
  distinct() 

scatter_plot_r2_fdr_df <- left_join(scatter_plot_r2_df, split_ofc_encoding_df_fdr)


scatter_plot_r2_fdr_df <- scatter_plot_r2_fdr_df %>%
  mutate(sig = if_else(mean_dis > mean_adv & perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05, "Disadvantageous", 
                       if_else(mean_adv >= mean_dis & perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05, "Advantegous", "Not Sig.")))

```


### Figure 3.d

```{r post-choice}
# prep for matlab #

both_var_results <- scatter_plot_r2_fdr_df %>%
  filter((predictor == "other_var_payoff" | predictor == "self_var_payoff") & epoch == "post-choice") %>%
  arrange(sig) %>%
  group_by(subject, electrode, predictor) %>%
  mutate(sig_fact = factor(sig, levels = c("Not Sig.", "Advantegous", "Disadvantageous"))) %>%
  mutate(sig_num = as.numeric(sig_fact) - 1) %>% # so 0, 1, 2
  select(sig_num, predictor, subject, electrode) %>%
  distinct() %>%
  pivot_wider(names_from = predictor, values_from = sig_num) %>%
  rowwise() %>%
  # mutate(null_total = sum((presentation == 0) + (`pre-choice` == 0) + (`post-choice` == 0))) %>%
  # mutate(adv_total = sum((presentation == 1) + (`pre-choice` == 1) + (`post-choice` == 1))) %>%
  # mutate(dis_total = sum((presentation == 2) + (`pre-choice` == 2) + (`post-choice` == 2))) %>%
  mutate(null_total = sum((self_var_payoff == 0) + (other_var_payoff == 0))) %>%
  mutate(adv_total = sum((self_var_payoff == 1) + (other_var_payoff == 1))) %>%
  mutate(dis_total = sum((self_var_payoff == 2) + (other_var_payoff == 2))) %>%
  mutate(figure_color = if_else(null_total == 2, 0, if_else(adv_total > 0 & dis_total > 0, 2, if_else(adv_total > 0, 1, if_else(dis_total > 0, 3, 5))))) %>%
  mutate(figure_elegend = if_else(null_total == 2, "Null", if_else(adv_total > 0 & dis_total > 0, "Adv & Dis", if_else(adv_total > 0, "Adv", if_else(dis_total > 0, "Dis", "Exception"))))) %>%
  rename(bipolar_name = electrode) %>%
  mutate(electrode = gsub("-.*", "", bipolar_name)) %>%
  select(subject, electrode, bipolar_name, figure_color, figure_elegend) %>%
  arrange(subject, electrode)

### bilateral ###
write_csv(both_var_results, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters.csv"))

for(sub in unique(both_var_results$subject)){
  
  tmp <- both_var_results %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters.csv")))


}

### left ###
left_ofc_elecs <- both_var_results %>% # ST40's OFG grid is on the left, otherwise the anatomy script figures it out by electrode names
  filter( (grepl("^AVF", electrode) | grepl("^MVF", electrode) | grepl("^FG", electrode) | grepl("^PVF", electrode) & subject == "ST40") | 
            (electrode %in% c("OF1", "OF2", "OF3") & subject == "ST40") | (subject != "ST40" & subject != "GP51")) %>%
  filter(subject %in% c("ST40") | grepl("^L", electrode) )

write_csv(left_ofc_elecs, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_left.csv"))

for(sub in unique(left_ofc_elecs$subject)){
  
  tmp <- left_ofc_elecs %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_left.csv")))


}


### right ###
right_ofc_elecs <- both_var_results %>% # GP51's OFG grid is on the right, , otherwise the anatomy script figures it out by electrode names
 filter( (grepl("^OFG", electrode) & subject == "GP51") | (electrode %in% c("OF4", "OF5") & subject == "ST40") |  subject != "GP51") %>%
 filter(subject %in% c("GP51") | grepl("^R", electrode))
    

write_csv(right_ofc_elecs, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_right.csv"))

for(sub in unique(right_ofc_elecs$subject)){
  
  tmp <- right_ofc_elecs %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_right.csv")))


}


```


### supplement

```{r pre-choice}
# prep for matlab #

both_var_results <- scatter_plot_r2_fdr_df %>%
  filter((predictor == "other_var_payoff" | predictor == "self_var_payoff") & epoch == "pre-choice") %>%
  arrange(sig) %>%
  group_by(subject, electrode, predictor) %>%
  mutate(sig_fact = factor(sig, levels = c("Not Sig.", "Advantegous", "Disadvantageous"))) %>%
  mutate(sig_num = as.numeric(sig_fact) - 1) %>% # so 0, 1, 2
  select(sig_num, predictor, subject, electrode) %>%
  distinct() %>%
  pivot_wider(names_from = predictor, values_from = sig_num) %>%
  rowwise() %>%
  # mutate(null_total = sum((presentation == 0) + (`pre-choice` == 0) + (`post-choice` == 0))) %>%
  # mutate(adv_total = sum((presentation == 1) + (`pre-choice` == 1) + (`post-choice` == 1))) %>%
  # mutate(dis_total = sum((presentation == 2) + (`pre-choice` == 2) + (`post-choice` == 2))) %>%
  mutate(null_total = sum((self_var_payoff == 0) + (other_var_payoff == 0))) %>%
  mutate(adv_total = sum((self_var_payoff == 1) + (other_var_payoff == 1))) %>%
  mutate(dis_total = sum((self_var_payoff == 2) + (other_var_payoff == 2))) %>%
  mutate(figure_color = if_else(null_total == 2, 0, if_else(adv_total > 0 & dis_total > 0, 2, if_else(adv_total > 0, 1, if_else(dis_total > 0, 3, 5))))) %>%
  mutate(figure_elegend = if_else(null_total == 2, "Null", if_else(adv_total > 0 & dis_total > 0, "Adv & Dis", if_else(adv_total > 0, "Adv", if_else(dis_total > 0, "Dis", "Exception"))))) %>%
  rename(bipolar_name = electrode) %>%
  mutate(electrode = gsub("-.*", "", bipolar_name)) %>%
  select(subject, electrode, bipolar_name, figure_color, figure_elegend) %>%
  arrange(subject, electrode)

### bilateral ###
write_csv(both_var_results, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_prec.csv"))

for(sub in unique(both_var_results$subject)){
  
  tmp <- both_var_results %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_prec.csv")))


}

### left ###
left_ofc_elecs <- both_var_results %>% # ST40's OFG grid is on the left, otherwise the anatomy script figures it out by electrode names
  filter( (grepl("^AVF", electrode) | grepl("^MVF", electrode) | grepl("^FG", electrode) | grepl("^PVF", electrode) & subject == "ST40") | 
            (electrode %in% c("OF1", "OF2", "OF3") & subject == "ST40") | (subject != "ST40" & subject != "GP51")) %>%
  filter(subject %in% c("ST40") | grepl("^L", electrode) )

write_csv(left_ofc_elecs, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_prec_left.csv"))

for(sub in unique(left_ofc_elecs$subject)){
  
  tmp <- left_ofc_elecs %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_prec_left.csv")))


}


### right ###
right_ofc_elecs <- both_var_results %>% # GP51's OFG grid is on the right, , otherwise the anatomy script figures it out by electrode names
 filter( (grepl("^OFG", electrode) & subject == "GP51") | (electrode %in% c("OF4", "OF5") & subject == "ST40") |  subject != "GP51") %>%
 filter(subject %in% c("GP51") | grepl("^R", electrode))
    

write_csv(right_ofc_elecs, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_prec_right.csv"))

for(sub in unique(right_ofc_elecs$subject)){
  
  tmp <- right_ofc_elecs %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_prec_right.csv")))


}


```


```{r presentation}
# prep for matlab #

both_var_results <- scatter_plot_r2_fdr_df %>%
  filter((predictor == "other_var_payoff" | predictor == "self_var_payoff") & epoch == "presentation") %>%
  arrange(sig) %>%
  group_by(subject, electrode, predictor) %>%
  mutate(sig_fact = factor(sig, levels = c("Not Sig.", "Advantegous", "Disadvantageous"))) %>%
  mutate(sig_num = as.numeric(sig_fact) - 1) %>% # so 0, 1, 2
  select(sig_num, predictor, subject, electrode) %>%
  distinct() %>%
  pivot_wider(names_from = predictor, values_from = sig_num) %>%
  rowwise() %>%
  # mutate(null_total = sum((presentation == 0) + (`pre-choice` == 0) + (`post-choice` == 0))) %>%
  # mutate(adv_total = sum((presentation == 1) + (`pre-choice` == 1) + (`post-choice` == 1))) %>%
  # mutate(dis_total = sum((presentation == 2) + (`pre-choice` == 2) + (`post-choice` == 2))) %>%
  mutate(null_total = sum((self_var_payoff == 0) + (other_var_payoff == 0))) %>%
  mutate(adv_total = sum((self_var_payoff == 1) + (other_var_payoff == 1))) %>%
  mutate(dis_total = sum((self_var_payoff == 2) + (other_var_payoff == 2))) %>%
  mutate(figure_color = if_else(null_total == 2, 0, if_else(adv_total > 0 & dis_total > 0, 2, if_else(adv_total > 0, 1, if_else(dis_total > 0, 3, 5))))) %>%
  mutate(figure_elegend = if_else(null_total == 2, "Null", if_else(adv_total > 0 & dis_total > 0, "Adv & Dis", if_else(adv_total > 0, "Adv", if_else(dis_total > 0, "Dis", "Exception"))))) %>%
  rename(bipolar_name = electrode) %>%
  mutate(electrode = gsub("-.*", "", bipolar_name)) %>%
  select(subject, electrode, bipolar_name, figure_color, figure_elegend) %>%
  arrange(subject, electrode)

### bilateral ###
write_csv(both_var_results, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_pres.csv"))

for(sub in unique(both_var_results$subject)){
  
  tmp <- both_var_results %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_pres.csv")))


}

### left ###
left_ofc_elecs <- both_var_results %>% # ST40's OFG grid is on the left, otherwise the anatomy script figures it out by electrode names
  filter( (grepl("^AVF", electrode) | grepl("^MVF", electrode) | grepl("^FG", electrode) | grepl("^PVF", electrode) & subject == "ST40") | 
            (electrode %in% c("OF1", "OF2", "OF3") & subject == "ST40") | (subject != "ST40" & subject != "GP51")) %>%
  filter(subject %in% c("ST40") | grepl("^L", electrode) )

write_csv(left_ofc_elecs, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_pres_left.csv"))

for(sub in unique(left_ofc_elecs$subject)){
  
  tmp <- left_ofc_elecs %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_pres_left.csv")))


}


### right ###
right_ofc_elecs <- both_var_results %>% # GP51's OFG grid is on the right, , otherwise the anatomy script figures it out by electrode names
 filter( (grepl("^OFG", electrode) & subject == "GP51") | (electrode %in% c("OF4", "OF5") & subject == "ST40") |  subject != "GP51") %>%
 filter(subject %in% c("GP51") | grepl("^R", electrode))
    

write_csv(right_ofc_elecs, path(here(), "figures", "anat_values", "ofc_electrodes_both_var_clusters_pres_right.csv"))

for(sub in unique(right_ofc_elecs$subject)){
  
  tmp <- right_ofc_elecs %>% filter(subject == sub)
  write.csv(tmp, path(here(), "figures", "anat_values", paste0(sub, "_ofc_electrodes_both_var_clusters_pres_right.csv")))


}


```
