---
title: "Inequity Dependent Encoding"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo <- FALSE,  # don't print the code chunk
  warning <- FALSE,  # don't print warnings
  message <- FALSE,  # don't print messages
  fig.width <- 5,  # set default width of figures
  fig.height <- 8,  # set default height of figures
  fig.align <- "center",  # always align figure in center
  fig.pos <- "H",  # always plot figure at the exact location of the code chunk
  cache <- FALSE)  # cache results

## libraries ##
library(tidyverse)
library(ggplot2)
library(magrittr)
# library(summarytools)
library(ggthemr)
library(grid)
library(gtable)
library(gridExtra)
library(wesanderson)
library(ggsci)
library(zoo)
library(kableExtra)
library(lme4)
library(RColorBrewer)
library(doParallel)
library(parallel)
library(foreach)
library(here)
library(fs)
library(ggcorrplot)
library(viridis)
library(lmtest)
library(gt)
library(ggalluvial)
library(parameters)
library(factoextra)
library(NbClust)
library(ggsankey)

## hand written functions ##
source(path(here(), "R", "load_behave_data.R"))
source(path(here(), "R", "prep_behave_data.R"))
source(path(here(), "R", "stretch_start_end.R"))
source(path(here(), "R", "load_high_gamma_data.R"))
source(path(here(), "R", "rolling_window_and_baseline.R"))
source(path(here(), "R", "compile_mult_reg_results.R"))
source(path(here(), "R", "compile_mult_reg_results.R"))
# source('~/Projects/nice_r_functions/ggpaired_pretty.R')
source(path(here(), "R", 'mutate_cond.R'))
source(path(here(), "R", "load_and_collate_reg_results.R"))



## plotting helpers ##
ggthemr("solarized")
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)

# ## parallelization ##
# nCores <- 4
# registerDoParallel(nCores)
# 


#find . -type f -mtime +10 -maxdepth 1 -exec mv {} before_3-21-21 \;
```


```{r load-data}
# load permuted regressor results #
split_ofc_encoding_reg_df <- read_csv(path(here(), "results", "single_regressions",
                                       "compiled_ofc_ogpermutation_wpvalues_single_regressions_1_28_2022.csv"))

# load permuted trial results #
split_ofc_encoding_ttype_df <- read_csv(path(here(), "results", "single_regressions",
                                       "compiled_ofc_ogpermutation_ttype_wpvalues_single_regressions_1_28_2022.csv"))

# rename test stats and combine #
split_ofc_encoding_reg_df <- split_ofc_encoding_reg_df %>%
  rename(test_stat_real_reg = test_stat_real) %>%
  rename(permuted_p_reg = permuted_p)

split_ofc_encoding_ttype_df <- split_ofc_encoding_ttype_df %>%
  rename(test_stat_real_ttype = test_stat_real) %>%
  rename(permuted_p_ttype = permuted_p)

split_ofc_encoding_df <- full_join(split_ofc_encoding_reg_df, split_ofc_encoding_ttype_df)


```

```{r alternate-hyp-removal}

## electrodes with differences in noise between trial types ##
trial_dep_noise_df <- read_csv(path(here(), "results", "trial_dep_differences_noise.csv"))


## electrodes better explained by max/min unified encoding ##
split_v_uni_max_df <- read_csv(path(here(), "results", "unified_max_split_elecs.csv"))

```

```{r prep-dfs}

## exclude elecs from alt explanantion analyses ##
split_ofc_encoding_df <- split_ofc_encoding_df %>%
  mutate(elec_epoch_ids = paste(subject, electrode, epoch, sep = "_")) %>%
  mutate_cond(elec_epoch_ids %in% trial_dep_noise_df$elec_epoch_ids, permuted_p_reg =1, permuted_p_ttype = 1) %>%
  mutate_cond(reg_id %in% split_v_uni_max_df$reg_id, permuted_p_reg =1, permuted_p_ttype = 1)


# percentage of elecs acros epochs
split_ofc_encoding_reg_sig <- split_ofc_encoding_df %>%
  filter(permuted_p_reg < 0.05) %>%
  select(subject, electrode, predictor, epoch, permuted_p_reg) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100)

split_ofc_encoding_ttype_sig <- split_ofc_encoding_df %>%
  filter(permuted_p_ttype < 0.05) %>%
  select(subject, electrode, predictor, epoch, permuted_p_ttype) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100)


split_ofc_encoding_sig <- split_ofc_encoding_df %>%
  filter(permuted_p_ttype < 0.05 & permuted_p_reg < 0.05) %>%
  select(subject, electrode, predictor, epoch, permuted_p_ttype, permuted_p_reg) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100)


# fdr correctyed df 
split_ofc_encoding_df_fdr <- split_ofc_encoding_df %>%
  select(reg_id, subject, electrode, predictor, epoch, permuted_p_reg, permuted_p_ttype) %>%
  distinct() %>%
  group_by(epoch, predictor) %>%
  mutate(perm_p_reg_fdr = p.adjust(permuted_p_reg, method = "fdr")) %>%
  mutate(perm_p_ttype_fdr = p.adjust(permuted_p_ttype, method = "fdr"))


scatter_plot_r2_df <- split_ofc_encoding_df %>%
  group_by(reg_id) %>%
  mutate(mean_adv = mean(Advantageous)) %>%
  mutate(mean_dis = mean(Disadvantageous)) %>%
  select(mean_adv, mean_dis, reg_id) %>%
  distinct() 

scatter_plot_r2_fdr_df <- left_join(scatter_plot_r2_df, split_ofc_encoding_df_fdr)


scatter_plot_r2_fdr_df <- scatter_plot_r2_fdr_df %>%
  mutate(sig = if_else(mean_dis > mean_adv & perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05, "Disadvantageous", 
                       if_else(mean_adv >= mean_dis & perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05, "Advantageous", "Not Sig.")))

```



```{r load-raw-hfa-data, echo = F}

# load hfa data #
all_brain_data_pres <-  read_csv(path(here(), "/munge/all_brain_data_pres_1_3_2022.csv"), 
                                 col_types = cols())
all_brain_data_pre_choice <-  read_csv(path(here(), "/munge/all_brain_data_pre_choice_1_3_2022.csv"), 
                                       col_types = cols())
all_brain_data_post_choice <-  read_csv(path(here(), "/munge/all_brain_data_post_choice_1_3_2022.csv"),
                                        col_types = cols())

```

```{r visualize-counts}

split_ofc_encoding_reg_sig %>%
  ggplot(., aes(x = predictor, fill = predictor)) +
  geom_hline(yintercept = 5, linetype = "dashed") +
  geom_bar(aes(y = after_stat( (count / 136) * 100))) +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~epoch) +
  labs(y = "Percentage of Electrodes", subtitle = "Best  Predictors",x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding: permuted reg")


split_ofc_encoding_ttype_sig %>%
  ggplot(., aes(x = predictor, fill = predictor)) +
  geom_hline(yintercept = 5, linetype = "dashed") +
  geom_bar(aes(y = after_stat( (count / 136) * 100))) +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~epoch) +
  labs(y = "Percentage of Electrodes", subtitle = "Best  Predictors",x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding: permuted trial")


split_ofc_encoding_sig %>%
  ggplot(., aes(x = predictor, fill = predictor)) +
  geom_hline(yintercept = 5, linetype = "dashed") +
  geom_bar(aes(y = after_stat( (count / 136) * 100))) +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~epoch) +
  labs(y = "Percentage of Electrodes", subtitle = "Best  Predictors",x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding: both permuted")

split_ofc_encoding_df %>%
  select(subject, electrode, predictor, epoch, permuted_p_reg, permuted_p_ttype) %>%
  distinct() %>%
  filter(predictor %in% best_preds) %>%
  group_by(predictor, subject) %>%
  mutate(num_of_elecs = n()) %>%
  mutate(percent_sub_elecs = sum(permuted_p_reg < 0.05 & permuted_p_ttype < 0.05)/num_of_elecs) %>%
  select(subject, predictor, percent_sub_elecs) %>%
  distinct() %>%
  ggplot(., aes(x = predictor, y = percent_sub_elecs, fill = predictor)) +
  geom_col() +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject, scales = "free_y") +
  labs(y = "Percent of Subject's Electrodes", subtitle = "Best  Predictors",x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding")


split_ofc_encoding_df %>%
  select(subject, electrode, predictor, epoch, permuted_p_reg, permuted_p_ttype) %>%
  distinct() %>%
  group_by(predictor, subject) %>%
  mutate(num_of_elecs = n()) %>%
  mutate(percent_sub_elecs = sum(permuted_p_reg < 0.05 & permuted_p_ttype < 0.05)) %>%
  select(subject, predictor, percent_sub_elecs) %>%
  distinct() %>%
  ggplot(., aes(x = predictor, y = percent_sub_elecs, fill = predictor)) +
  geom_col() +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject, scales = "free_y") +
  labs(y = "Number of Subject's Electrodes", x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding")

```



```{r visualize-counts-fdr}

percent_elecs_split_encoding_plot <- split_ofc_encoding_df_fdr %>%
  filter(perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05) %>%
  mutate(predictor = if_else(predictor == "ineq_var_abs", "Absolute Inequity",
                             if_else(predictor == "max", "Max", 
                                     if_else(predictor == "min", "Min",
                                             if_else(predictor == "other_var_payoff", "Other Offer",
                                                if_else(predictor == "self_var_payoff", "Self Offer", 
                                                    if_else(predictor == "trial_type", "Trial Type", "NA"))))))) %>%
  mutate(epoch = factor(epoch, levels = c("presentation", "pre-choice", "post-choice"))) %>%
  ggplot(., aes(x = predictor, fill = predictor)) +
  geom_bar(aes(y = after_stat( (count / 136) * 100))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        panel.background = element_rect(fill = "white"),
        legend.position = "none",
        strip.text =  element_text(family = "Georgia", color = '#2D2327', size = 16),
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 16),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 16),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 14), 
        plot.title = element_text(family = "Georgia", color = '#2D2327', size = 18)) + 
  facet_wrap(~epoch) +
  labs(y = "Percentage of Electrodes", x = "") +
  scale_fill_manual(values = c("#DE4A4D", "#FFD680", "#88D1A3", "#3D99BA")) +
  ggtitle("Ineq. Dependent Encoding by Epoch and Predictor")


ggsave(filename = path(here(), "figures", "paper", "split_encoding_percent_elecs_plot.tif"),
     device = "tiff",
     width = 14,
     height = 12,
     units = "in",
     dpi = 350,
     plot =  percent_elecs_split_encoding_plot)

## table
split_hfa_fdr_sig_table <- split_ofc_encoding_df_fdr %>%
  filter(perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05) %>%
  select(subject, electrode, predictor, epoch) %>%
  distinct() %>%
  group_by(predictor, epoch) %>%
  mutate(sig_count_per_epoch = n()) %>%
  mutate(percent_of_elecs_per_epoch = (sig_count_per_epoch/ 136) * 100) %>%
  group_by(predictor) %>%
  mutate(sig_count = n()) %>%
  mutate(percent_of_elecs = (sig_count/ 136) * 100) %>%
  select(predictor, epoch, sig_count_per_epoch, percent_of_elecs_per_epoch, sig_count, percent_of_elecs) %>%
  distinct() %>%
  mutate(percent_of_elecs_per_epoch = round(percent_of_elecs_per_epoch, 2)) %>%
  mutate(percent_of_elecs = round(percent_of_elecs, 2)) %>%
  arrange(desc(predictor), desc(epoch))  %>%
  mutate(predictor = if_else(predictor == "self_var_payoff", "Self-Offer",
                                     if_else(predictor == "other_var_payoff", "Other-Offer",
                                             if_else(predictor == "max", "Max", "Min"))))

## by subject
split_ofc_encoding_df_fdr %>%
  select(subject, electrode, predictor, epoch, perm_p_reg_fdr, perm_p_ttype_fdr) %>%
  distinct() %>%
  filter(predictor %in% best_preds) %>%
  group_by(predictor, subject) %>%
  mutate(num_of_elecs = n()) %>%
  mutate(percent_sub_elecs = sum(perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05)/num_of_elecs) %>%
  select(subject, predictor, percent_sub_elecs) %>%
  distinct() %>%
  ggplot(., aes(x = predictor, y = percent_sub_elecs, fill = predictor)) +
  geom_col() +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject, scales = "free_y") +
  labs(y = "Percent of Subject's Electrodes", subtitle = "Best  Predictors",x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding")


split_ofc_encoding_df_fdr %>%
  select(subject, electrode, predictor, epoch,  perm_p_reg_fdr, perm_p_ttype_fdr) %>%
  distinct() %>%
  group_by(predictor, subject, epoch) %>%
  mutate(num_of_elecs = n()) %>%
  mutate(percent_sub_elecs = sum(perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05)) %>%
  select(subject, predictor, percent_sub_elecs) %>%
  distinct() %>%
  ggplot(., aes(x = predictor, y = percent_sub_elecs, fill = predictor)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_blank(), panel.background = element_rect(fill = "white")) +
  facet_wrap(~subject, scales = "free_y") +
  labs(y = "Number of Subject's Electrodes", x = "predictors") +
  scale_fill_manual(values = getPalette(6)) +
  ggtitle("HFA Split Encoding")

```


```{r example-raw-data-plot}

adv_plot <- all_brain_data_post_choice %>%
  filter(subject == "ST40" & electrodes == "FG17" & trial_type == "Advantageous") %>%
  pivot_longer(cols = starts_with("post_"), values_to = "HFA", names_to = "bin") %>%
  mutate(time = 50 * as.numeric(gsub("post_", "", bin))) %>%
  filter(time <= 1000) %>%
  ggplot(., aes(x = self_var_payoff, y = HFA)) +
  geom_point(color = "#5BA6D6") +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', fill = 'grey') +
  facet_wrap(~time, nrow = 1) +
  labs(x = "Self Offer", subtitle = "Advantageous Trials") +
  theme(panel.background = element_blank(), legend.position = "top",
        strip.text = element_blank(),
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 18),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 16), 
        plot.subtitle = element_text(family = "Georgia", color = '#2D2327', size = 20),
        axis.text.x = element_blank(), axis.ticks.x = element_blank())

dis_plot <- all_brain_data_post_choice %>%
  filter(subject == "ST40" & electrodes == "FG17" & trial_type == "Disadvantageous") %>%
  pivot_longer(cols = starts_with("post_"), values_to = "HFA", names_to = "bin") %>%
  mutate(time = 50 * as.numeric(gsub("post_", "", bin))) %>%
  filter(time <= 1000) %>%
  ggplot(., aes(x = self_var_payoff, y = HFA)) +
  geom_point(color = "#E4635C") +
  geom_smooth(method = 'lm', formula = 'y~x', color = 'black', fill = 'grey') +
  facet_wrap(~time, nrow = 1) +
  labs(x = "Self Offer", subtitle = "Disadvantageous Trials") +
  theme(panel.background = element_blank(), legend.position = "top",
        strip.text = element_blank(),
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 18),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 16), 
        plot.subtitle = element_text(family = "Georgia", color = '#2D2327', size = 20),
        axis.text.x = element_blank(), axis.ticks.x = element_blank())


ggsave(filename = path(here(), "figures", "paper", "hfa_self_example_plots.tif"),
     device = "tiff",
     width = 10,
     height = 12,
     units = "in",
     dpi = 350,
     plot =   arrangeGrob(grobs = list(adv_plot, dis_plot), nrow = 2, ncol = 1))


```



```{r example-elecs-r2}

sig_split_elecs_df <- scatter_plot_r2_fdr_df %>%
  filter(perm_p_reg_fdr < 0.05 & perm_p_ttype_fdr < 0.05)


# sample self var in adv
example_selfv_elec_stats <- sig_split_elecs_df %>%
  ungroup() %>%
  filter(reg_id %in% c("GP51_OFG46_self_var_payoff_pre-choice", "GP51_OFG46_self_var_payoff_post-choice")) ## fdr permuted p ~ 0


example_selfva_elec_df <- split_ofc_encoding_df %>%
  ungroup() %>%
  filter(reg_id %in% c("GP51_OFG46_self_var_payoff_pre-choice", "GP51_OFG46_self_var_payoff_post-choice")) %>%
  mutate(time = if_else(epoch == "pre-choice", -50 * as.numeric(gsub("pre_", "", bin)),
                        50 * as.numeric(gsub("post_", "", bin)))) %>%
  pivot_longer(cols = c(Disadvantageous, Advantageous), names_to = "State", values_to = "R2") 

self_adv_plot <- example_selfva_elec_df %>%
  ggplot(., aes(x = time, y = R2, color = State)) +
  geom_vline(xintercept = 0, color = 'black', linetype = 'dashed') +
  geom_point() +
  geom_line() +
  # ylim(0, .22) +
  theme(panel.background = element_blank(), legend.position = "top",
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 18),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 16), 
        plot.subtitle = element_text(family = "Georgia", color = '#2D2327', size = 18),
        plot.title = element_text(family = "Georgia", color = '#2D2327', size = 20)) + 
  labs(x = "Time (in ms)", color = "", subtitle = "Example Electrode 1", title = "Self Offer Encoded Only in Adv. Trials")

# sample self var in dis
self_dis_split <- sig_split_elecs_df %>%
  filter(predictor == "self_var_payoff" & sig == "Disadvantageous")

example_selfvd_elec_df <- split_ofc_encoding_df %>%
  ungroup() %>%
  filter(reg_id %in% c("GP51_OFG22_self_var_payoff_pre-choice", "GP51_OFG22_self_var_payoff_post-choice")) %>%
  mutate(time = if_else(epoch == "pre-choice", -50 * as.numeric(gsub("pre_", "", bin)),
                        50 * as.numeric(gsub("post_", "", bin)))) %>%
  pivot_longer(cols = c(Disadvantageous, Advantageous), names_to = "State", values_to = "R2") 

self_dis_plot <- example_selfvd_elec_df %>%
  ggplot(., aes(x = time, y = R2, color = State)) +
  geom_vline(xintercept = 0, color = 'black', linetype = 'dashed') +
  geom_point() +
  geom_line() +
  # ylim(0, .22) +
  theme(panel.background = element_blank(), legend.position = "top",
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 18),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 16), 
        plot.subtitle = element_text(family = "Georgia", color = '#2D2327', size = 18),
        plot.title = element_text(family = "Georgia", color = '#2D2327', size = 20)) + 
  labs(x = "Time (in ms)", color = "", subtitle = "Example Electrode 2", title = "Self Offer Encoded Only in Dis. Trials")


# sample other var in adv
other_adv_split <- scatter_plot_r2_fdr_df %>%
  filter(predictor == "other_var_payoff" & sig == "Advantegous")

example_othera_elec_df <- split_ofc_encoding_df %>%
  ungroup() %>%
  filter(reg_id %in% c("GP51_OFG60_other_var_payoff_pre-choice", "GP51_OFG60_other_var_payoff_post-choice")) %>%
  mutate(time = if_else(epoch == "pre-choice", -50 * as.numeric(gsub("pre_", "", bin)),
                        50 * as.numeric(gsub("post_", "", bin)))) %>%
  pivot_longer(cols = c(Disadvantageous, Advantageous), names_to = "State", values_to = "R2") 

other_adv_plot <- example_othera_elec_df %>%
  ggplot(., aes(x = time, y = R2, color = State)) +
  geom_vline(xintercept = 0, color = 'black', linetype = 'dashed') +
  geom_point() +
  geom_line() +
  # ylim(0, .22) +
  theme(panel.background = element_blank(), legend.position = "top",
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 18),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 16), 
        plot.subtitle = element_text(family = "Georgia", color = '#2D2327', size = 18),
        plot.title = element_text(family = "Georgia", color = '#2D2327', size = 20)) + 
  labs(x = "Time (in ms)", color = "", subtitle = "Example Electrode 3", title = "Other Offer Encoded Only in Adv. Trials")


# sample other var in dis
other_dis_split <- scatter_plot_r2_fdr_df %>%
  filter(predictor == "other_var_payoff" & sig == "Disadvantageous")

example_othervd_elec_df <- split_ofc_encoding_df %>%
  ungroup() %>%
  filter(reg_id %in% c("GP51_OFG43_other_var_payoff_pre-choice", "GP51_OFG43_other_var_payoff_post-choice")) %>%
  mutate(time = if_else(epoch == "pre-choice", -50 * as.numeric(gsub("pre_", "", bin)),
                        50 * as.numeric(gsub("post_", "", bin)))) %>%
  pivot_longer(cols = c(Disadvantageous, Advantageous), names_to = "State", values_to = "R2") 

other_dis_plot <- example_othervd_elec_df %>%
  ggplot(., aes(x = time, y = R2, color = State)) +
  geom_vline(xintercept = 0, color = 'black', linetype = 'dashed') +
  geom_point() +
  geom_line() +
  # ylim(0, .22) +
  theme(panel.background = element_blank(), legend.position = "top",
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 18),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 18),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 16),
        plot.subtitle = element_text(family = "Georgia", color = '#2D2327', size = 18),
        plot.title = element_text(family = "Georgia", color = '#2D2327', size = 20)) + 
  labs(x = "Time (in ms)", color = "", subtitle = "Example Electrode 4", title = "Other Offer Encoded Only in Dis. Trials")



plot(arrangeGrob(grobs = list(self_adv_plot, self_dis_plot, other_adv_plot, other_dis_plot), nrow = 2, ncol = 2))


ggsave(filename = path(here(), "figures", "paper", "r2_plots.tif"),
     device = "tiff",
     width = 13,
     height = 13,
     units = "in",
     dpi = 350,
     plot =   arrangeGrob(grobs = list(self_adv_plot, self_dis_plot, other_adv_plot, other_dis_plot), nrow = 2, ncol = 2))



```


```{r flow-plot}

alluv_split_table <- scatter_plot_r2_fdr_df %>%
  ungroup() %>%
  mutate(elec_id = paste0(subject, "_", electrode)) %>%
  select(elec_id, predictor, epoch, sig) %>%
  distinct() %>%
  pivot_wider(names_from = epoch, values_from = sig) %>%
  filter(!(presentation == 'Not Sig.' & `pre-choice` == 'Not Sig.' & `post-choice` == 'Not Sig.')) %>%
  group_by(presentation, `pre-choice`, `post-choice`) %>%
  add_count()

alluv_split_df <- scatter_plot_r2_fdr_df %>%
  ungroup() %>%
  select(subject, electrode, predictor, epoch, sig) %>%
  mutate(elec_id = paste0(subject, "_", electrode)) %>%
  distinct() %>%
  pivot_wider(names_from = epoch, values_from = sig) %>%
  filter(!(presentation == 'Not Sig.' & `pre-choice` == 'Not Sig.' & `post-choice` == 'Not Sig.')) %>%
  group_by(presentation, `pre-choice`, `post-choice`) %>%
  add_count() %>%
  select(presentation, `pre-choice`, `post-choice`, n, elec_id) %>%
  ungroup() %>%
  make_long(presentation, `pre-choice`, `post-choice`) %>%
  mutate(node = factor(node, 
                       levels = c('Not Sig.', 'Advantageous', 'Disadvantageous', 'NA'),
                       labels = c('      Not Sig.      ', '   Advantageous   ', 'Disadvantageous', 'NA'), exclude = 'none')) %>%
  mutate(next_node = factor(next_node, 
                            levels = c('Not Sig.', 'Advantageous', 'Disadvantageous', 'NA'), 
                            labels = c('      Not Sig.      ', '   Advantageous   ', 'Disadvantageous', 'NA'), exclude = 'none'))


alluvial_plot <- ggplot(alluv_split_df, aes(x = x, 
               next_x = next_x, 
               node = node, 
               next_node = next_node,
               label = node,
               fill = node)) +
  geom_alluvial(flow.alpha = 0.75, node.color = 1, width = .4) +
  geom_alluvial_label(color = "white",  size = 3.5) +
  labs(x = "", y = "Electrode Count", fill = "Predictor", title = "State-dependent inequity encoding type is consistent across epochs") +
  theme(panel.background = element_rect(fill = "white"),
        legend.position = 'none', 
        legend.title = element_text(family = "Georgia", color = '#2D2327', size = 16),
        legend.text = element_text(family = "Georgia", color = '#2D2327', size = 16),
        axis.title = element_text(family = "Georgia", color = '#2D2327', size = 18), 
        axis.text = element_text(family = "Georgia", color = '#2D2327', size = 14), 
        plot.title = element_text(family = "Georgia", color = '#2D2327', size = 14, hjust = .5)) +
        scale_fill_manual(values = c('grey', "#5BA6D6", "#E4635C"))



ggsave(filename = path(here(), "figures", "paper", "split_encoding_alluvial_plot.tif"),
     device = "tiff",
     width =11,
     height = 3.7,
     units = "in",
     dpi = 350,
     plot =   alluvial_plot)
 
```



```{r encoding-self_and-other}


both_var_results <- scatter_plot_r2_fdr_df %>%
  filter((predictor == "other_var_payoff" | predictor == "self_var_payoff")) %>%
  arrange(sig) %>%
  group_by(subject, electrode, predictor, epoch) %>%
  mutate(sig_fact = factor(sig, levels = c("Not Sig.", "Advantegous", "Disadvantageous"))) %>%
  mutate(sig_num = as.numeric(sig_fact) - 1) %>% # so 0, 1, 2
  select(sig_num, predictor, subject, electrode) %>%
  distinct() %>%
  pivot_wider(names_from = predictor, values_from = sig_num) %>%
  rowwise() %>%
  # mutate(null_total = sum((presentation == 0) + (`pre-choice` == 0) + (`post-choice` == 0))) %>%
  # mutate(adv_total = sum((presentation == 1) + (`pre-choice` == 1) + (`post-choice` == 1))) %>%
  # mutate(dis_total = sum((presentation == 2) + (`pre-choice` == 2) + (`post-choice` == 2))) %>%
  mutate(null_total = sum((self_var_payoff == 0) + (other_var_payoff == 0))) %>%
  mutate(adv_total = sum((self_var_payoff == 1) + (other_var_payoff == 1))) %>%
  mutate(dis_total = sum((self_var_payoff == 2) + (other_var_payoff == 2))) %>%
  filter(null_total == 0)

brain_behave_elec <- all_brain_data_pres %>%
  filter(subject == "GP51" & electrodes == "OFG22")


self_plot <-  brain_behave_elec %>%
  filter(trial_type == "Disadvantageous") %>%
  pivot_longer(cols = starts_with("bin_"), values_to = "HFA", names_to = "bin") %>%
  mutate(time = 50 * as.numeric(gsub("bin_", "", bin))) %>%
  filter(time <= 1000) %>%
  ggplot(., aes(x = self_var_payoff)) +
  geom_point(aes(y = HFA), color = "orange") +
  geom_smooth(aes(y = HFA), color = 'black', fill = 'grey', method = "lm", formula = 'y ~ x') +
  theme(panel.background = element_rect(fill = "white"), axis.title.x = element_blank()) +
  facet_wrap(~time, nrow = 1) + 
  scale_x_continuous(n.breaks = 3)

other_plot <-  brain_behave_elec %>%
  filter(trial_type == "Disadvantageous") %>%
  pivot_longer(cols = starts_with("bin_"), values_to = "HFA", names_to = "bin") %>%
  mutate(time = 50 * as.numeric(gsub("bin_", "", bin))) %>%
  filter(time <= 1000) %>%
  ggplot(., aes(x = other_var_payoff)) +
  geom_point(aes(y = HFA), color = "pink") +
  geom_smooth(aes(y = HFA), color = 'black', fill = 'grey', method = "lm", formula = 'y ~ x') +
  theme(panel.background = element_rect(fill = "white")) +
  scale_x_continuous(n.breaks = 3) +
  facet_wrap(~time, nrow = 1)

   
 print(plot( arrangeGrob(grobs = list(self_plot,other_plot), nrow = 2, ncol = 1)))


```



